MNGHATR1208v2

diff --git a/.github/workflows/auto-round.yml b/.github/workflows/auto-round.yml
--- a/.github/workflows/auto-round.yml
+++ b/.github/workflows/auto-round.yml
@@ -2,11 +2,14 @@ name: Auto Round Cron
 on:
   schedule:
     - cron: '0 12 * * *'  # 12:00 UTC daily
-  workflow_dispatch:  # Cho manual test
+  workflow_dispatch:  # For manual test
 
 jobs:
   trigger-auto-round:
     runs-on: ubuntu-latest
     steps:
       - name: Call API Endpoint
-        run: curl -X GET "https://miniis-3.vercel.app/api/auto-round" -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" -f || echo "Fail - check logs"
+        run: |
+          curl -X GET "https://miniis-3.vercel.app/api/auto-round" \
+          -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
+          -f || echo "Fail - check logs"
